
server:
  port: 2020

spring:
  application:
    name: elasticsearch
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  resources:
    static-locations: classpath:/








